// 又拍云
const UP_YUN_BUCKET = 'wash-car-shop'
const UP_YUN_API = 'https://v0.api.upyun.com/wash-car-shop'
const UP_YUN_DELETE_API = 'http://v0.api.upyun.com/wash-car-shop'
const UP_YUN_IMAGE_DOMAIN = 'wash-car-shop.test.upcdn.net'
const UP_YUN_IMAGE_PATH = '/images/'
const UP_YUN_OPERATOR = 'washcarshop'
const UP_YUN_PASSWORD = '2RVdpcGzHYL1MdvufMGgf7p7DsEOjzzM'

// 内部消息
const EDIT_WEIGHT_MESSAGE = 'editWeightMessage'
const EDIT_PRICE_MESSAGE = 'editPriceMessage'
const EDIT_DISCOUNT_MESSAGE = 'editDiscountMessage'
const UPDATE_ANNOUNCE_MESSAGE = 'updateAnnounceMessage'
const UPDATE_GOODS_MESSAGE = 'updateGoodsMessage'
const UPDATE_PAY_TYPE_MESSAGE = 'updatePayTypeMessage'
const UPDATE_CAR_MODEL_MESSAGE = 'updateCarModelMessage'
const UPDATE_SHOP_MESSAGE = 'updateShopMessage'

module.exports = {
  UP_YUN_BUCKET: UP_YUN_BUCKET,
  UP_YUN_API: UP_YUN_API,
  UP_YUN_IMAGE_DOMAIN: UP_YUN_IMAGE_DOMAIN,
  UP_YUN_IMAGE_PATH: UP_YUN_IMAGE_PATH,
  UP_YUN_OPERATOR: UP_YUN_OPERATOR,
  UP_YUN_PASSWORD: UP_YUN_PASSWORD,
  EDIT_WEIGHT_MESSAGE: EDIT_WEIGHT_MESSAGE,
  EDIT_PRICE_MESSAGE: EDIT_PRICE_MESSAGE,
  EDIT_DISCOUNT_MESSAGE: EDIT_DISCOUNT_MESSAGE,
  UPDATE_ANNOUNCE_MESSAGE: UPDATE_ANNOUNCE_MESSAGE,
  UPDATE_GOODS_MESSAGE: UPDATE_GOODS_MESSAGE,
  UPDATE_PAY_TYPE_MESSAGE: UPDATE_PAY_TYPE_MESSAGE,
  UPDATE_CAR_MODEL_MESSAGE: UPDATE_CAR_MODEL_MESSAGE,
  UPDATE_SHOP_MESSAGE: UPDATE_SHOP_MESSAGE,
  UP_YUN_DELETE_API: UP_YUN_DELETE_API

}